### ISSUE TITLE
Discarded operations when the processing queue is full

### ISSUE THREAD

**Issue by slux83** [dariol83/reatmetric#1]
The method `eu.dariolucia.reatmetric.processing.impl.ProcessingModelImpl#scheduleTask(...)` submits the operations using the `offer()` to the blocking queues that were previously created with a limited capacity. If the queue is full the `offer()` will return `false` but at the current state this is not taken into consideration and the operation is simply discarded.

**Comment by dariol83** [comment]
Thank you for spotting this, you are right. The implementation is now changed to introduce backpressure in case the queue is full, so that the data is not discarded anymore. This change introduces a potential risk of deadlock in case of internal operations. The code has a TODO to cover this part (hopefully soon). I leave the issue open, until the TODO is implemented.
